all: forktest1 forktest2 forktest3 forktest4

forktest1: forktest1.c
	-gcc -ansi -pedantic -g -o forktest1 forktest1.c

forktest2: forktest2.c
	-gcc -ansi -pedantic -g -o forktest2 forktest2.c

forktest3: forktest3.c
	-gcc -ansi -pedantic -g -o forktest3 forktest3.c

forktest4: forktest4.c
	-gcc -ansi -pedantic -g -o forktest4 forktest4.c
